[package]
name = "bike-share-anomaly-detection"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
extended-isolation-forest = "0.2.3"
serde = { version = "1.0.207", features = ["derive"] }
